package br.com.ftathiago.docman.model;
// Generated 03/11/2017 02:54:03 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContaReceber generated by hbm2java
 */
@Entity
@Table(name = "conta_receber")
public class ContaReceber implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int crecId;
	private ContaMovimento contaMovimento;
	private ModoPagamento modoPagamento;
	private Pessoa pessoa;
	private String crecDescricao;
	private Date crecCriacao;
	private Date crecVencimento;
	private Date crecPagamento;
	private double crecValor;
	private Double crecValorPago;

	public ContaReceber() {
	}

	public ContaReceber(int crecId, ContaMovimento contaMovimento, ModoPagamento modoPagamento, String crecDescricao,
			Date crecCriacao, Date crecVencimento, double crecValor) {
		this.crecId = crecId;
		this.contaMovimento = contaMovimento;
		this.modoPagamento = modoPagamento;
		this.crecDescricao = crecDescricao;
		this.crecCriacao = crecCriacao;
		this.crecVencimento = crecVencimento;
		this.crecValor = crecValor;
	}

	public ContaReceber(int crecId, ContaMovimento contaMovimento, ModoPagamento modoPagamento, Pessoa pessoa,
			String crecDescricao, Date crecCriacao, Date crecVencimento, Date crecPagamento, double crecValor,
			Double crecValorPago) {
		this.crecId = crecId;
		this.contaMovimento = contaMovimento;
		this.modoPagamento = modoPagamento;
		this.pessoa = pessoa;
		this.crecDescricao = crecDescricao;
		this.crecCriacao = crecCriacao;
		this.crecVencimento = crecVencimento;
		this.crecPagamento = crecPagamento;
		this.crecValor = crecValor;
		this.crecValorPago = crecValorPago;
	}

	@Id

	@Column(name = "CREC_ID", unique = true, nullable = false)
	public int getCrecId() {
		return this.crecId;
	}

	public void setCrecId(int crecId) {
		this.crecId = crecId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CMOV_ID", nullable = false)
	public ContaMovimento getContaMovimento() {
		return this.contaMovimento;
	}

	public void setContaMovimento(ContaMovimento contaMovimento) {
		this.contaMovimento = contaMovimento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MPGT_ID", nullable = false)
	public ModoPagamento getModoPagamento() {
		return this.modoPagamento;
	}

	public void setModoPagamento(ModoPagamento modoPagamento) {
		this.modoPagamento = modoPagamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PESS_ID_DEVEDOR")
	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	@Column(name = "CREC_DESCRICAO", nullable = false, length = 250)
	public String getCrecDescricao() {
		return this.crecDescricao;
	}

	public void setCrecDescricao(String crecDescricao) {
		this.crecDescricao = crecDescricao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREC_CRIACAO", nullable = false, length = 10)
	public Date getCrecCriacao() {
		return this.crecCriacao;
	}

	public void setCrecCriacao(Date crecCriacao) {
		this.crecCriacao = crecCriacao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREC_VENCIMENTO", nullable = false, length = 10)
	public Date getCrecVencimento() {
		return this.crecVencimento;
	}

	public void setCrecVencimento(Date crecVencimento) {
		this.crecVencimento = crecVencimento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREC_PAGAMENTO", length = 10)
	public Date getCrecPagamento() {
		return this.crecPagamento;
	}

	public void setCrecPagamento(Date crecPagamento) {
		this.crecPagamento = crecPagamento;
	}

	@Column(name = "CREC_VALOR", nullable = false, precision = 22, scale = 0)
	public double getCrecValor() {
		return this.crecValor;
	}

	public void setCrecValor(double crecValor) {
		this.crecValor = crecValor;
	}

	@Column(name = "CREC_VALOR_PAGO", precision = 22, scale = 0)
	public Double getCrecValorPago() {
		return this.crecValorPago;
	}

	public void setCrecValorPago(Double crecValorPago) {
		this.crecValorPago = crecValorPago;
	}

}
