package br.com.ftathiago.docman.model;
// Generated 03/11/2017 02:54:03 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DocHistorico generated by hbm2java
 */
@Entity
@Table(name = "doc_historico")
public class DocHistorico implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer dhstId;
	private Documento documento;
	private Pessoa pessoa;
	private byte dhstAlterado;
	private Date dhstDataBloqueio;
	private Date dhstDataDesbloqueio;

	public DocHistorico() {
	}

	public DocHistorico(Documento documento, byte dhstAlterado, Date dhstDataBloqueio) {
		this.documento = documento;
		this.dhstAlterado = dhstAlterado;
		this.dhstDataBloqueio = dhstDataBloqueio;
	}

	public DocHistorico(Documento documento, Pessoa pessoa, byte dhstAlterado, Date dhstDataBloqueio,
			Date dhstDataDesbloqueio) {
		this.documento = documento;
		this.pessoa = pessoa;
		this.dhstAlterado = dhstAlterado;
		this.dhstDataBloqueio = dhstDataBloqueio;
		this.dhstDataDesbloqueio = dhstDataDesbloqueio;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DHST_ID", unique = true, nullable = false)
	public Integer getDhstId() {
		return this.dhstId;
	}

	public void setDhstId(Integer dhstId) {
		this.dhstId = dhstId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DCMT_ID", nullable = false)
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PESS_ID")
	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	@Column(name = "DHST_ALTERADO", nullable = false)
	public byte getDhstAlterado() {
		return this.dhstAlterado;
	}

	public void setDhstAlterado(byte dhstAlterado) {
		this.dhstAlterado = dhstAlterado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DHST_DATA_BLOQUEIO", nullable = false, length = 19)
	public Date getDhstDataBloqueio() {
		return this.dhstDataBloqueio;
	}

	public void setDhstDataBloqueio(Date dhstDataBloqueio) {
		this.dhstDataBloqueio = dhstDataBloqueio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DHST_DATA_DESBLOQUEIO", length = 19)
	public Date getDhstDataDesbloqueio() {
		return this.dhstDataDesbloqueio;
	}

	public void setDhstDataDesbloqueio(Date dhstDataDesbloqueio) {
		this.dhstDataDesbloqueio = dhstDataDesbloqueio;
	}

}
