package br.com.ftathiago.docman.model;
// Generated 03/11/2017 02:54:03 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Documento generated by hbm2java
 */
@Entity
@Table(name = "documento")
public class Documento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer dcmtId;
	private Pessoa pessoa;
	private Processo processo;
	private TipoDocumento tipoDocumento;
	private byte dcmtBloqueado;
	private String dcmtTitulo;
	private Set<DocHistorico> docHistoricos = new HashSet<DocHistorico>(0);
	private Set<DocVersao> docVersaos = new HashSet<DocVersao>(0);

	public Documento() {
	}

	public Documento(Pessoa pessoa, Processo processo, TipoDocumento tipoDocumento, byte dcmtBloqueado,
			String dcmtTitulo) {
		this.pessoa = pessoa;
		this.processo = processo;
		this.tipoDocumento = tipoDocumento;
		this.dcmtBloqueado = dcmtBloqueado;
		this.dcmtTitulo = dcmtTitulo;
	}

	public Documento(Pessoa pessoa, Processo processo, TipoDocumento tipoDocumento, byte dcmtBloqueado,
			String dcmtTitulo, Set<DocHistorico> docHistoricos, Set<DocVersao> docVersaos) {
		this.pessoa = pessoa;
		this.processo = processo;
		this.tipoDocumento = tipoDocumento;
		this.dcmtBloqueado = dcmtBloqueado;
		this.dcmtTitulo = dcmtTitulo;
		this.docHistoricos = docHistoricos;
		this.docVersaos = docVersaos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DCMT_ID", unique = true, nullable = false)
	public Integer getDcmtId() {
		return this.dcmtId;
	}

	public void setDcmtId(Integer dcmtId) {
		this.dcmtId = dcmtId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PESS_ID_ENVIOU", nullable = false)
	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROC_ID", nullable = false)
	public Processo getProcesso() {
		return this.processo;
	}

	public void setProcesso(Processo processo) {
		this.processo = processo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TDOC_ID", nullable = false)
	public TipoDocumento getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(TipoDocumento tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@Column(name = "DCMT_BLOQUEADO", nullable = false)
	public byte getDcmtBloqueado() {
		return this.dcmtBloqueado;
	}

	public void setDcmtBloqueado(byte dcmtBloqueado) {
		this.dcmtBloqueado = dcmtBloqueado;
	}

	@Column(name = "DCMT_TITULO", nullable = false, length = 250)
	public String getDcmtTitulo() {
		return this.dcmtTitulo;
	}

	public void setDcmtTitulo(String dcmtTitulo) {
		this.dcmtTitulo = dcmtTitulo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documento")
	public Set<DocHistorico> getDocHistoricos() {
		return this.docHistoricos;
	}

	public void setDocHistoricos(Set<DocHistorico> docHistoricos) {
		this.docHistoricos = docHistoricos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documento")
	public Set<DocVersao> getDocVersaos() {
		return this.docVersaos;
	}

	public void setDocVersaos(Set<DocVersao> docVersaos) {
		this.docVersaos = docVersaos;
	}

}
