package br.com.ftathiago.docman.model;
// Generated 03/11/2017 02:54:03 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DverConteudo generated by hbm2java
 */
@Entity
@Table(name = "dver_conteudo")
public class DverConteudo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer dverId;
	private byte[] dverConteudo;

	public DverConteudo() {
	}

	public DverConteudo(byte[] dverConteudo) {
		this.dverConteudo = dverConteudo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DVER_ID", unique = true, nullable = false)
	public Integer getDverId() {
		return this.dverId;
	}

	public void setDverId(Integer dverId) {
		this.dverId = dverId;
	}

	@Column(name = "DVER_CONTEUDO", nullable = false)
	public byte[] getDverConteudo() {
		return this.dverConteudo;
	}

	public void setDverConteudo(byte[] dverConteudo) {
		this.dverConteudo = dverConteudo;
	}

}
