package br.com.ftathiago.docman.model;
// Generated 03/11/2017 02:54:03 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModoPagamento generated by hbm2java
 */
@Entity
@Table(name = "modo_pagamento")
public class ModoPagamento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int mpgtId;
	private String mpgtDescricao;
	private Set<ContaPagar> contaPagars = new HashSet<ContaPagar>(0);
	private Set<ContaReceber> contaRecebers = new HashSet<ContaReceber>(0);

	public ModoPagamento() {
	}

	public ModoPagamento(int mpgtId) {
		this.mpgtId = mpgtId;
	}

	public ModoPagamento(int mpgtId, String mpgtDescricao, Set<ContaPagar> contaPagars,
			Set<ContaReceber> contaRecebers) {
		this.mpgtId = mpgtId;
		this.mpgtDescricao = mpgtDescricao;
		this.contaPagars = contaPagars;
		this.contaRecebers = contaRecebers;
	}

	@Id

	@Column(name = "MPGT_ID", unique = true, nullable = false)
	public int getMpgtId() {
		return this.mpgtId;
	}

	public void setMpgtId(int mpgtId) {
		this.mpgtId = mpgtId;
	}

	@Column(name = "MPGT_DESCRICAO", length = 45)
	public String getMpgtDescricao() {
		return this.mpgtDescricao;
	}

	public void setMpgtDescricao(String mpgtDescricao) {
		this.mpgtDescricao = mpgtDescricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modoPagamento")
	public Set<ContaPagar> getContaPagars() {
		return this.contaPagars;
	}

	public void setContaPagars(Set<ContaPagar> contaPagars) {
		this.contaPagars = contaPagars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modoPagamento")
	public Set<ContaReceber> getContaRecebers() {
		return this.contaRecebers;
	}

	public void setContaRecebers(Set<ContaReceber> contaRecebers) {
		this.contaRecebers = contaRecebers;
	}

}
