package br.com.ftathiago.docman.model;
// Generated 03/11/2017 02:54:03 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Pessoa generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "pessoa")
public class Pessoa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer pessId;
	private String pessNome;

	public Pessoa() {
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PESS_ID", unique = true, nullable = false)
	public Integer getPessId() {
		return this.pessId;
	}

	public void setPessId(Integer pessId) {
		this.pessId = pessId;
	}

	@Column(name = "PESS_NOME", length = 100)
	public String getPessNome() {
		return this.pessNome;
	}

	public void setPessNome(String pessNome) {
		this.pessNome = pessNome;		
	}
}
