package br.com.ftathiago.docman.model;
// Generated 03/11/2017 02:54:03 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProcParte generated by hbm2java
 */
@Entity
@Table(name = "proc_parte")
public class ProcParte implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer pparId;
	private Pessoa pessoa;
	private Processo processo;
	private TipoParte tipoParte;

	public ProcParte() {
	}

	public ProcParte(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	public ProcParte(Pessoa pessoa, Processo processo, TipoParte tipoParte) {
		this.pessoa = pessoa;
		this.processo = processo;
		this.tipoParte = tipoParte;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PPAR_ID", unique = true, nullable = false)
	public Integer getPparId() {
		return this.pparId;
	}

	public void setPparId(Integer pparId) {
		this.pparId = pparId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PESS_ID", nullable = false)
	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROC_ID")
	public Processo getProcesso() {
		return this.processo;
	}

	public void setProcesso(Processo processo) {
		this.processo = processo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TPPR_ID")
	public TipoParte getTipoParte() {
		return this.tipoParte;
	}

	public void setTipoParte(TipoParte tipoParte) {
		this.tipoParte = tipoParte;
	}

}
