package br.com.ftathiago.docman.model;
// Generated 03/11/2017 02:54:03 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Processo generated by hbm2java
 */
@Entity
@Table(name = "processo")
public class Processo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer procId;
	private int cmrcId;
	private String procNumero;
	private int varaId;
	private Set<Documento> documentos = new HashSet<Documento>(0);
	private Set<ProcParte> procPartes = new HashSet<ProcParte>(0);

	public Processo() {
	}

	public Processo(int cmrcId, int varaId) {
		this.cmrcId = cmrcId;
		this.varaId = varaId;
	}

	public Processo(int cmrcId, String procNumero, int varaId, Set<Documento> documentos, Set<ProcParte> procPartes) {
		this.cmrcId = cmrcId;
		this.procNumero = procNumero;
		this.varaId = varaId;
		this.documentos = documentos;
		this.procPartes = procPartes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PROC_ID", unique = true, nullable = false)
	public Integer getProcId() {
		return this.procId;
	}

	public void setProcId(Integer procId) {
		this.procId = procId;
	}

	@Column(name = "CMRC_ID", nullable = false)
	public int getCmrcId() {
		return this.cmrcId;
	}

	public void setCmrcId(int cmrcId) {
		this.cmrcId = cmrcId;
	}

	@Column(name = "PROC_NUMERO", length = 45)
	public String getProcNumero() {
		return this.procNumero;
	}

	public void setProcNumero(String procNumero) {
		this.procNumero = procNumero;
	}

	@Column(name = "VARA_ID", nullable = false)
	public int getVaraId() {
		return this.varaId;
	}

	public void setVaraId(int varaId) {
		this.varaId = varaId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "processo")
	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "processo")
	public Set<ProcParte> getProcPartes() {
		return this.procPartes;
	}

	public void setProcPartes(Set<ProcParte> procPartes) {
		this.procPartes = procPartes;
	}

}
