package br.com.ftathiago.docman.model;
// Generated 03/11/2017 02:54:03 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RegrasSistema generated by hbm2java
 */
@Entity
@Table(name = "regras_sistema")
public class RegrasSistema implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String nome;
	private Set<UsuarioRegrasSistema> usuarioRegrasSistemas = new HashSet<UsuarioRegrasSistema>(0);

	public RegrasSistema() {
	}

	public RegrasSistema(String nome) {
		this.nome = nome;
	}

	public RegrasSistema(String nome, Set<UsuarioRegrasSistema> usuarioRegrasSistemas) {
		this.nome = nome;
		this.usuarioRegrasSistemas = usuarioRegrasSistemas;
	}

	@Id

	@Column(name = "nome", unique = true, nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regrasSistema")
	public Set<UsuarioRegrasSistema> getUsuarioRegrasSistemas() {
		return this.usuarioRegrasSistemas;
	}

	public void setUsuarioRegrasSistemas(Set<UsuarioRegrasSistema> usuarioRegrasSistemas) {
		this.usuarioRegrasSistemas = usuarioRegrasSistemas;
	}

}
