package br.com.ftathiago.docman.model;
// Generated 03/11/2017 02:54:03 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioRegrasSistemaId generated by hbm2java
 */
@Embeddable
public class UsuarioRegrasSistemaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int usuarioPessId;
	private String regrasSistemasNome;

	public UsuarioRegrasSistemaId() {
	}

	public UsuarioRegrasSistemaId(int usuarioPessId, String regrasSistemasNome) {
		this.usuarioPessId = usuarioPessId;
		this.regrasSistemasNome = regrasSistemasNome;
	}

	@Column(name = "Usuario_PESS_ID", nullable = false)
	public int getUsuarioPessId() {
		return this.usuarioPessId;
	}

	public void setUsuarioPessId(int usuarioPessId) {
		this.usuarioPessId = usuarioPessId;
	}

	@Column(name = "regrasSistemas_nome", nullable = false)
	public String getRegrasSistemasNome() {
		return this.regrasSistemasNome;
	}

	public void setRegrasSistemasNome(String regrasSistemasNome) {
		this.regrasSistemasNome = regrasSistemasNome;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioRegrasSistemaId))
			return false;
		UsuarioRegrasSistemaId castOther = (UsuarioRegrasSistemaId) other;

		return (this.getUsuarioPessId() == castOther.getUsuarioPessId())
				&& ((this.getRegrasSistemasNome() == castOther.getRegrasSistemasNome())
						|| (this.getRegrasSistemasNome() != null && castOther.getRegrasSistemasNome() != null
								&& this.getRegrasSistemasNome().equals(castOther.getRegrasSistemasNome())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUsuarioPessId();
		result = 37 * result + (getRegrasSistemasNome() == null ? 0 : this.getRegrasSistemasNome().hashCode());
		return result;
	}

}
