package br.com.ftathiago.docman.model;
// Generated 03/11/2017 02:54:03 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario")
public class Usuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer pessId;
	private String pusuLogin;
	private String pusuSenha;
	private Set<UsuarioRegrasSistema> usuarioRegrasSistemas = new HashSet<UsuarioRegrasSistema>(0);
	private Set<UsuarioRoles> usuarioRoleses = new HashSet<UsuarioRoles>(0);

	public Usuario() {
	}

	public Usuario(String pusuLogin, String pusuSenha) {
		this.pusuLogin = pusuLogin;
		this.pusuSenha = pusuSenha;
	}

	public Usuario(String pusuLogin, String pusuSenha, Set<UsuarioRegrasSistema> usuarioRegrasSistemas,
			Set<UsuarioRoles> usuarioRoleses) {
		this.pusuLogin = pusuLogin;
		this.pusuSenha = pusuSenha;
		this.usuarioRegrasSistemas = usuarioRegrasSistemas;
		this.usuarioRoleses = usuarioRoleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PESS_ID", unique = true, nullable = false)
	public Integer getPessId() {
		return this.pessId;
	}

	public void setPessId(Integer pessId) {
		this.pessId = pessId;
	}

	@Column(name = "PUSU_LOGIN", nullable = false, length = 45)
	public String getPusuLogin() {
		return this.pusuLogin;
	}

	public void setPusuLogin(String pusuLogin) {
		this.pusuLogin = pusuLogin;
	}

	@Column(name = "PUSU_SENHA", nullable = false, length = 250)
	public String getPusuSenha() {
		return this.pusuSenha;
	}

	public void setPusuSenha(String pusuSenha) {
		this.pusuSenha = pusuSenha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioRegrasSistema> getUsuarioRegrasSistemas() {
		return this.usuarioRegrasSistemas;
	}

	public void setUsuarioRegrasSistemas(Set<UsuarioRegrasSistema> usuarioRegrasSistemas) {
		this.usuarioRegrasSistemas = usuarioRegrasSistemas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioRoles> getUsuarioRoleses() {
		return this.usuarioRoleses;
	}

	public void setUsuarioRoleses(Set<UsuarioRoles> usuarioRoleses) {
		this.usuarioRoleses = usuarioRoleses;
	}

}
