package br.com.ftathiago.docman.model;
// Generated 03/11/2017 02:54:03 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UsuarioRoles generated by hbm2java
 */
@Entity
@Table(name = "usuario_roles", uniqueConstraints = { @UniqueConstraint(columnNames = "ROLE_ID"),
		@UniqueConstraint(columnNames = "PESS_ID") })
public class UsuarioRoles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private UsuarioRolesId id;
	private Usuario usuario;

	public UsuarioRoles() {
	}

	public UsuarioRoles(UsuarioRolesId id, Usuario usuario) {
		this.id = id;
		this.usuario = usuario;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "pessId", column = @Column(name = "PESS_ID", unique = true, nullable = false)),
			@AttributeOverride(name = "roleId", column = @Column(name = "ROLE_ID", unique = true, nullable = false)) })
	public UsuarioRolesId getId() {
		return this.id;
	}

	public void setId(UsuarioRolesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PESS_ID", unique = true, nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
