package br.com.ftathiago.docman.model;
// Generated 03/11/2017 02:54:03 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioRolesId generated by hbm2java
 */
@Embeddable
public class UsuarioRolesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int pessId;
	private int roleId;

	public UsuarioRolesId() {
	}

	public UsuarioRolesId(int pessId, int roleId) {
		this.pessId = pessId;
		this.roleId = roleId;
	}

	@Column(name = "PESS_ID", unique = true, nullable = false)
	public int getPessId() {
		return this.pessId;
	}

	public void setPessId(int pessId) {
		this.pessId = pessId;
	}

	@Column(name = "ROLE_ID", unique = true, nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioRolesId))
			return false;
		UsuarioRolesId castOther = (UsuarioRolesId) other;

		return (this.getPessId() == castOther.getPessId()) && (this.getRoleId() == castOther.getRoleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPessId();
		result = 37 * result + this.getRoleId();
		return result;
	}

}
